extends: default

rules:
  line-length:
    max: 100
    level: warning
  indentation:
    indent-sequences: consistent
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  trailing-spaces:
    level: error

